STOCKFISH_API_URL = "Stock fish API URL"
STOCKFISH_API_KEY = "YOUR_STOCKFISH_API_KEY"
GEMINI_API_KEY     = "YOUR_GEMINI_API_KEY"
GEMINI_MODEL       = "chat-bison-001"
GAME_ID            = ""
GAME_PGN_URL       = f"https://www.chess.com/game/live/{GAME_ID}/pgn"
POLL_INTERVAL      = 2    # in seconds
DEPTH              = 15   # Stockfish search depth
SWING_THRESHOLD    = 0.10 